/**
 * `standards init` — bootstrap a project into this framework.
 *
 * THE SAFETY CONTRACT, and the reason plan and apply are separate functions:
 *
 *   plan(dir)            decides what would happen, touching nothing
 *   apply(dir, plan)     executes exactly that plan
 *
 * `--dry-run` prints the plan; a real run executes it. There is no second code path that works out
 * what to do — because a dry-run that derives its own idea of the work is not a preview of anything,
 * and the gap between the two is exactly where a destructive surprise lives.
 *
 * Three actions, and the distinction between them matters:
 *
 *   create    the file does not exist; it will be written
 *   skip      the file exists and already came from this framework; it is left alone
 *   conflict  the file exists and did NOT come from this framework; it is left alone and reported
 *
 * Nothing is ever overwritten. A project's own project-policy.yml is a considered document — the
 * applicability reasons in it are judgements someone made — and replacing it with a template would
 * destroy work that cannot be recovered from the template. Idempotence matters for the same reason:
 * a second run must find what the first wrote and leave it exactly as it is.
 */

import { readFile, writeFile, mkdir, access } from "node:fs/promises";
import path from "node:path";

/** Marker written into generated files so a later run can tell its own output from a project's work. */
const MARKER = "generated by: standards init";

const TEMPLATES = [
  { template: "project-policy.yml", target: "project-policy.yml" },
  { template: "betting-policy.yml", target: "betting-policy.yml" },
  { template: "AGENTS.md", target: "AGENTS.md" },
  { template: "CLAUDE.md", target: "CLAUDE.md" },
  { template: "decision-record.example.json", target: "ledger/.template.json" },
];

async function exists(p) {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
}

/**
 * Decide what init would do. Reads only.
 *
 * Returns an array of { path, action, template, reason }. The array IS the plan: apply() executes it
 * without re-deciding anything.
 */
export async function plan(dir, frameworkRoot) {
  // frameworkRoot is where templates/ lives.
  const operations = [];

  for (const { template, target } of TEMPLATES) {
    const targetPath = path.join(dir, target);
    const relative = target;

    if (!(await exists(targetPath))) {
      operations.push({ path: relative, action: "create", template, reason: "does not exist" });
      continue;
    }

    // The file is there. Whether it is ours decides between skip and conflict, and getting this
    // wrong in the permissive direction would mean overwriting someone's considered policy.
    let content = "";
    try {
      content = await readFile(targetPath, "utf8");
    } catch {
      operations.push({ path: relative, action: "conflict", template, reason: "exists but could not be read" });
      continue;
    }

    // Two ways a file can be recognised as ours. The marker covers anything that can carry a
    // comment. JSON cannot, and a marker field would make the file fail its own schema — so for
    // those, being byte-identical to the template is the signal. Without this second test, init
    // reports a file it wrote itself as a conflict on the very next run, which would train an
    // operator to ignore conflict reports.
    let templateBody = null;
    try {
      templateBody = await readFile(path.join(frameworkRoot, "templates", template), "utf8");
    } catch {
      templateBody = null;
    }
    const isOurs = content.includes(MARKER) || (templateBody !== null && content === templateBody);

    if (isOurs) {
      operations.push({ path: relative, action: "skip", template, reason: "already generated by this framework" });
    } else {
      operations.push({
        path: relative,
        action: "conflict",
        template,
        reason: "exists and was not generated by this framework — left untouched",
      });
    }
  }

  // Resolve template sources so apply() does no discovery of its own.
  for (const op of operations) {
    op.source = path.join(frameworkRoot, "templates", op.template);
  }
  return operations;
}

/**
 * Execute a plan produced by plan(). Writes only files the plan marked `create`.
 *
 * Returns the same operations with a `done` flag, so a caller can report what actually happened
 * rather than what was intended.
 */
export async function apply(dir, operations) {
  const applied = [];
  for (const op of operations) {
    if (op.action !== "create") {
      applied.push({ ...op, done: false });
      continue;
    }
    const targetPath = path.join(dir, op.path);
    await mkdir(path.dirname(targetPath), { recursive: true });
    const body = await readFile(op.source, "utf8");
    await writeFile(targetPath, body, "utf8");
    applied.push({ ...op, done: true });
  }
  return applied;
}

export { MARKER };
